### ISSUE TITLE
Add missing Permissions for dandelion flow

### ISSUE THREAD

**Issue by rperez89** [1Hive/dandelion-org#15]

**Comment by lkngtn** [comment]
```
---
id: dandelion
tokens:
- ref: token
  symbol: "$token_symbol"
  name: "$token_name"
  decimals: 18
apps:
- ref: voting
  type: dandelion-voting
  token: token
  support: "$support_param"
  acceptance: "$acceptance_param"
  duration: "$vote_duration_param"
- ref: vote-delay
  type: delay
  duration: "$delay_duration_param"
- ref: dissent-oracle
  type: dissent-oracle
  duration: "$delay_duration_param + $voteduration_param"
  voting: "$voting"
- ref: time-lock
  type: time-lock
  amount: "$time_lock_amount_param"
  spamPenalty: "$spamPenalty_param"
- ref: balance-oracle
  type: balance-oracle
  amount: 0
  token: token
- ref: redemptions
  type: redemptions
  vault: agent
  token: token
  assets: "$asset_array_param"
- ref: tm
  type: token-manager
  token: token
  tranferrable: false
  max: 1
- ref: token-request
  type: token-request
  token-manager: tm
  vault: agent
  assets: "$asset_array_param"
- ref: agent
  type: agent
  default: true
permissions:
- app: kernel
  role: APP_MANAGER_ROLE
  grantee: vote-delay
  manager: vote-delay
- app: acl
  role: CREATE_PERMISSIONS_ROLE
  grantee: vote-delay
  manager: vote-delay
- app: voting
  role: CREATE_VOTES_ROLE
  grantee: time-lock
  manager: vote-delay
- app: time-lock
  role: LOCK_TOKENS_ROLE
  grantee: ANY_ENTITY
  oracle: balance-oracle
  manager: vote-delay
- app: voting
  role: MODIFY_QUORUM_ROLE
  grantee: vote-delay
  manager: vote-delay
- app: voting
  role: MODIFY_SUPPORT_ROLE
  grantee: vote-delay
  manager: vote-delay
- app: agent
  role: EXECUTE_ROLE
  grantee: vote-delay
  manager: vote-delay
- app: agent
  role: RUN_SCRIPT_ROLE
  grantee: vote-delay
  manager: vote-delay
- app: agent
  role: TRANSFER_ROLE
  grantee: redemptions
  manager: vote-delay
- app: tm
  role: BURN_ROLE
  grantee: vote-delay
  manager: vote-delay
- app: tm
  role: MINT_ROLE
  grantee: token-request
  manager: vote-delay
- app: token-request
  role: FINALISE_TOKEN_REQUEST_ROLE
  grantee: vote-delay
  manager: vote-delay
- app: vote-delay
  role: DELAY_EXECUTION_ROLE
  grantee: voting
  manager: vote-delay
```
